version: '3.9'

services:
  client:
    build: 
      context: ./client
      dockerfile: client.dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - serve

  serve:
    build: 
      context: ./serve
      dockerfile: serve.dockerfile
    volumes:
      - ./serve:/serve
      - data:/serve/app/data
    ports:
      - "8000:8000"
    
      


volumes:
  data: