"""empty message

Revision ID: 479a09df0a09
Revises: 
Create Date: 2022-02-17 18:04:16.517010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479a09df0a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_short', sa.String(length=10), nullable=True),
    sa.Column('link_origin', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_short')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
